# Generated by Django 6.0 on 2026-02-25 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_store_supplier_alter_item_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
